---
- name: Remove the cron job
  hosts: all

  tasks:
  - name: delete the cron job
    cron: 
      name: VAR
      env: yes
      user: pravin
      job: /home/pravin/shellpra/01.sh
      state: absent 
