---
- name: Firewall changes
  hosts: all

  tasks: 
  - name: Enable service in firewalld
    firewalld:
      port: 80/tcp
      permanent: true
      state: enabled

  - name: Reload firewalld
    service:
      name: firewalld
      state: reloaded
